name: Trigger upstream OpenAPI sync

on:
  push:
    paths:
      - "runner/openapi.json"
  workflow_dispatch:

jobs:
  trigger-sdks-openapi-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger experimental SDKs update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SDKS_TRIGGER_PAT }}
          repository: livepeer/livepeer-ai-sdks
          event-type: update-ai-openapi
          client-payload: '{"sha": "${{ github.sha }}"}'
        
      - name: Trigger released JS/TS SDK update
        # if: startsWith(github.ref, 'refs/tags/') # Only run on release.
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SDKS_TRIGGER_PAT }}
          repository: livepeer/ai-sdk-js
          event-type: update-ai-openapi
          client-payload: '{"sha": "${{ github.sha }}"}'

  trigger-docs-openapi-sync:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/') # Only run on release.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger docs AI OpenAPI spec update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DOCS_TRIGGER_PAT }}
          repository: rickstaa/docs
          event-type: update-ai-openapi
          client-payload: '{"sha": "${{ github.sha }}"}'
